import {
  Inter as Geist,
  Source_Code_Pro as Geist_Mono,
} from "next/font/google";
import "./globals.css";
import ThemeProviderClient from "./ThemeProviderClient";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata = {
  title: "Hi, I'm Suraj",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-black dark:text-white transition-colors duration-300`}
      >
        <ThemeProviderClient>{children}</ThemeProviderClient>
      </body>
    </html>
  );
}
